global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: node-exporter
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [nodejs_c_v2]
        target_label: instance