version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: spring-boot-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/demo_db
  #     - SPRING_DATASOURCE_USERNAME=demo_user
  #     - SPRING_DATASOURCE_PASSWORD=demo_password
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
